# Generated by Django 5.2.9 on 2026-01-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSERTS', 'Desserts'), ('BEVERAGES', 'Beverages'), ('BIRIYANI', 'Biryani')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
