# Generated by Django 5.2.9 on 2026-01-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_fooditems_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(default='None', max_length=100)),
                ('food_type', models.CharField(choices=[('REGULAR', 'Regular'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=100)),
                ('toppings', models.CharField(max_length=100)),
                ('sauce', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customizeimg/')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems')),
            ],
        ),
    ]
