# Generated by Django 5.2.9 on 2026-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_customize_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize_options',
            name='base',
            field=models.CharField(choices=[('MAIDA', 'Maida'), ('WHEAT', 'Wheat')], default='None', max_length=100),
        ),
    ]
