# Generated by Django 5.2.9 on 2026-01-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_basetype_sauce_sizechart_toppings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSERTS', 'Desserts'), ('BEVERAGES', 'Beverages'), ('BIRIYANI', 'Biryani')], max_length=100)),
                ('base', models.CharField(choices=[('MAIDA', 'Maida'), ('WHEAT', 'Wheat')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customizeimg/')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauces', to='foods.sauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='foods.sizechart')),
                ('toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='foods.toppings')),
            ],
        ),
    ]
