# Generated by Django 5.2.9 on 2026-01-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_customize_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizechart',
            name='size_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=100),
        ),
    ]
