# Generated by Django 5.2.9 on 2026-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_sizechart_size_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='cartimg/')),
            ],
        ),
    ]
