# Generated by Django 5.2.9 on 2026-01-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_rename_price_cart_total_price_remove_cart_food_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='foods.fooditems'),
        ),
        migrations.CreateModel(
            name='CustomizedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.basetype')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems')),
                ('sauce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.sauce')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.sizechart')),
                ('toppings', models.ManyToManyField(blank=True, to='foods.toppings')),
            ],
        ),
    ]
