# Generated by Django 5.2.9 on 2026-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
