# Generated by Django 5.2.9 on 2026-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0004_alter_userdetails_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('NORMAL_USER', 'normal_user')], default='user', max_length=100),
        ),
    ]
