# Generated by Django 5.2.9 on 2026-01-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0005_userdetails_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('NORMAL_USER', 'normal_user')], default='NORMAL_USER', max_length=100),
        ),
    ]
