# Generated by Django 5.2.9 on 2026-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0009_alter_userdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
